### ISSUE TITLE
Messages in php.doc aren't accessible

### ISSUE THREAD

**Issue by jimwins** [php/web-news#17]
The individual messages can't be accessed, for example https://news-web.php.net/php.doc/969388365 just shows "Error: No article found"

Also not accessible via NNTP, so it's probably a colobus issue of some sort.

**Comment by cmb69** [comment]
Could anyone with appropriate karma please look into this?

**Comment by derickr** [comment]
Hi,

the reason for this is that during the conversion between old and new server, we never actually migrated the archive of old messages, because they had a really odd numbering scheme. And in the hub hub of trying to deal with gmail non-sense, I had forgotten about this.

However, I spent some time this morning to address this, and it should now all work according to plan.

Let me know if you encounter something odd!

cheers,
Derick
